version: ~> 1.0
dist: jammy
language: node_js
node_js:
  - "18"
env:
  GRAPHQL_ORIGIN: "https://graphql.natwelch.com/graphql"
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
script:
  - yarn install
  - yarn run build
  - yarn run test
addons:
  artifacts: true
  working_dir: build
