language: node_js
node_js:
  - "16"
env:
  GRAPHQL_ORIGIN: "https://graphql.natwelch.com/graphql"
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn install
  - yarn run build
addons:
  artifacts: true
  working_dir: build
