language: node_js
node_js:
  - 'node'
env:
  GRAPHQL_ORIGIN: "https://graphql.natwelch.com/graphql"
cache:
  - yarn
script:
  - yarn install
  - yarn run build
addons:
  artifacts: true
  working_dir: build
