name: Check Markdown links
on:
  workflow_dispatch:
  schedule:
    # UTC
    - cron: 12 12 1 * *
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: .github/workflows/markdown-links-config.json
