name: Replace old links with archived links
on:
  schedule:
    - cron: "12 */6 * * *"
  workflow_dispatch:

# Add concurrency control to prevent multiple runs
concurrency:
  group: notfoundbot-workflow
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Fix links
        uses: tmcw/notfoundbot@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCEPTIONS: writing.natwelch.com
          # Add unique cache key to prevent conflicts
          CACHE_KEY: notfoundbot-${{ github.run_id }}
        with:
          content-folder: ./posts/
