name: bump-sitemap

on:
  workflow_dispatch:
  schedule:
    # UTC
    - cron: '12 0 * * *'

jobs:
  bump-sitemap:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - run: yarn
    - run: yarn run build
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'chore: generate sitemap'
