name: bump-sitemap

on:
  workflow_dispatch:
  schedule:
    # UTC
    - cron: '0 * * * *'

jobs:
  bump-sitemap:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install

    - name: Build
      uses: borales/actions-yarn@v4
      with:
        cmd: build

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: chore: generate sitemap
